### ISSUE TITLE
Support for other platforms

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/orjson-feedstock#15]
I looked at the discussion on `staged-recipes` about punting on `win` and `osx` and thought I would raise the issue that it would be nice to try to get these working. While ideally, we'd want to get both platforms supported, personally making progress on `osx` would be enough for me. 

Does anyone have thoughts about the path forward on this?

**Comment by EntPyle** [comment]
I'd love to get it up and running on osx and windows. It's been a while,
but I believe we had successful recipes for all at one point in the
process. It's just a matter of piecing together the different methods and
calling the appropriate commands per os, with one recipe. This is my first
time building a non-pure python recipe, so its a lot that was new to me.

**Comment by synapticarbors** [comment]
closed by #16
