### ISSUE TITLE
Switch to rust conda package

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/orjson-feedstock#33]
If possible, switch to using `{{ compiler('rust') }}` and simplify the recipe.

**Comment by nehaljwani** [comment]
Conda package for the nightly builds are built at https://github.com/conda-forge/rust-feedstock/tree/dev

**Comment by synapticarbors** [comment]
I think this is a good idea, but since `orjson` seems to move the nightly version that they recommend with every release, we're going to need to push the `dev` branch of the rust compiler forward as a prerequisite. Currently it looks like the latest is `2020-10-15`.

**Comment by synapticarbors** [comment]
Closed by #71
